tab_spaces = 2
max_width = 120
chain_width = 100
fn_call_width = 100
struct_lit_width = 40
attr_fn_like_width = 100
single_line_if_else_max_width = 100
spaces_around_ranges = true
force_multiline_blocks = true
use_field_init_shorthand = true

# unstable
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
control_brace_style = "ClosingNextLine"
overflow_delimited_expr = true
struct_lit_single_line = true
